Introduce travis (#5)
* added .travis.yml

* changed xcode_project

* changed xcode_scheme

* shared scheme

* added xcode_sdk (for “Code Sign error”?)

* specified osx_image

* added 10.2 to xcode_sdk

* specified “before_script” to build with xcodebuild

* specified “script” to avoid a Travis error
$ xctool -project Gengo.xcodeproj -scheme Gengo -sdk iphonesimulator10.2 build test
ERROR: Unexpected action: build

* use xcodebuild for testing

* removed “-sdk” to hopefully fix “xcodebuild: error: Unable to find a destination matching the provided destination specifier”

* removed the Carthage file to fix “The requested device could not be found because multiple devices matched the request.”

* changed destination name to iPad Retina

* removed before_script

* added a Travis status